/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Gym.NewHire;




import Business.EcoSystem;
import Business.HireApplications.NewHireApplication;
import Business.HireApplications.NewHireApplicationsDirectory;


import UI.MainJFrame;
import java.awt.CardLayout;
import java.awt.Window;
import java.awt.event.WindowEvent;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author akash
 */
public class NewHireJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewHireJPanel
     */
    
    private String username;
    private String password;
    private EcoSystem system;
    private JPanel nhJPanel;
    private MainJFrame frame2;
    private JPanel container;
    
    public NewHireJPanel(EcoSystem system, JPanel nhJPanel, MainJFrame frame) {
      
         initComponents();
        this.system = system;
        this.nhJPanel = nhJPanel;
        this.frame2 = frame;
        this.container = container;
    }
    
    public void close (){
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lastNameTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pfone = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        pftwo = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        cbxPosition = new javax.swing.JComboBox<>();
        btnSubmitApplication = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("User name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 223, -1, -1));

        txtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 165, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("First Name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        firstNameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(firstNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 165, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Last Name");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 186, -1, 18));

        lastNameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lastNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 165, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Password");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        pfone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(pfone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 165, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Re-enter the password");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, 18));

        pftwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pftwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pftwoActionPerformed(evt);
            }
        });
        jPanel1.add(pftwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 165, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Position");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, 30));

        cbxPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trainer", "Analyst", "Salesman" }));
        cbxPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPositionActionPerformed(evt);
            }
        });
        jPanel1.add(cbxPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 165, 30));

        btnSubmitApplication.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnSubmitApplication.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitApplication.setText("Submit Application");
        btnSubmitApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitApplicationActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitApplication, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 434, 157, 41));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void pftwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pftwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pftwoActionPerformed

    private void cbxPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPositionActionPerformed

    private void btnSubmitApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitApplicationActionPerformed
        // TODO add your handling code here:
       String username = txtUserName.getText();
        String position = cbxPosition.getSelectedItem().toString();
        
        if(!pfone.getText().equals(pftwo.getText())){
            
            JOptionPane.showMessageDialog(null, "Please enter the same passwords in both fields");
        }
        
        else {
        // Adding the new job application
        NewHireApplication nha = new NewHireApplication (username, position);
        
        JOptionPane.showMessageDialog(null, "Your application has been successfully submitted!");
        } 
    }//GEN-LAST:event_btnSubmitApplicationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmitApplication;
    private javax.swing.JComboBox<String> cbxPosition;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JPasswordField pfone;
    private javax.swing.JPasswordField pftwo;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
