/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Customer;

import Business.Booking.Booking;
import Business.Enterprise.GymEnterprise;
import Business.Accounts.UserAccount;
import Business.WorkQueue.BookingRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author keshni
 */
public class RequestTrainerJPanel extends javax.swing.JPanel {
    private JPanel container;
    private UserAccount account;
    private GymEnterprise gymenterprise;
    private DateFormat df;
    /**
     * Creates new form RequestTrainerJPanel
     */
    public RequestTrainerJPanel(JPanel container, UserAccount account, GymEnterprise fitenterprise) {
       initComponents();
        this.container = container;
        this.account = account;
        this.gymenterprise = fitenterprise;
        df = new SimpleDateFormat("yyyy-MM-dd");
        //df = new SimpleDateFormat("YYYY/MM/DD");
        populateComboBox();
    }
    public void populateComboBox() {
        cbxDateSelect.removeAll();
        for(Date date : gymenterprise.getAppointmentTime().getDateList()){
            cbxDateSelect.addItem(df.format(date));
        }
        cbxTimeSlotSelect.removeAll();
        for(String session : gymenterprise.getAppointmentTime().getSessionList()){
            cbxTimeSlotSelect.addItem(session);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backjButton = new javax.swing.JButton();
        BtnReserve = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cbxDateSelect = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbxTimeSlotSelect = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backjButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        backjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/back (1).png"))); // NOI18N
        backjButton.setText("Previous");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 17, -1, 50));

        BtnReserve.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnReserve.setForeground(new java.awt.Color(0, 102, 102));
        BtnReserve.setText("Confirm selected appointment");
        BtnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReserveActionPerformed(evt);
            }
        });
        add(BtnReserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 500, -1, 47));

        viewBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        viewBtn.setForeground(new java.awt.Color(0, 102, 102));
        viewBtn.setText("Show appointment status");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(869, 500, 279, 47));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        cbxDateSelect.setToolTipText("");
        cbxDateSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDateSelectActionPerformed(evt);
            }
        });
        cbxDateSelect.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbxDateSelectKeyPressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/calendar (1).png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Select a time slot ");

        cbxTimeSlotSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTimeSlotSelectActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/clock.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxTimeSlotSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(314, 314, 314))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(cbxDateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(cbxTimeSlotSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 88, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void cbxDateSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDateSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDateSelectActionPerformed

    private void cbxTimeSlotSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTimeSlotSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTimeSlotSelectActionPerformed

    private void BtnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReserveActionPerformed
        // TODO add your handling code here:
        String dateString = (String) cbxDateSelect.getSelectedItem();
        Date date = null;
        try {
            date = df.parse(dateString);
        } catch (ParseException ex) {
            Logger.getLogger(RequestTrainerJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        String session = (String) cbxTimeSlotSelect.getSelectedItem();
        for(BookingRequest appointmentRequest : account.getAppointmentQueue().getAppointmentRequestList()){
            if((appointmentRequest.getStatus().equals("Accept") || appointmentRequest.getStatus().equals("Pending")) && appointmentRequest.getAppointment().getDate().equals(date) && appointmentRequest.getAppointment().getSession().equals(session)){
                JOptionPane.showMessageDialog(null, "You already have appointment at that time");
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Successfully");
        Booking appointment = new Booking(date, session);
        BookingRequest appointmentRequest = new BookingRequest(appointment);
        appointmentRequest.setSender(account);
        appointmentRequest.setStatus("Pending");
        account.getAppointmentQueue().getAppointmentRequestList().add(appointmentRequest);
        gymenterprise.getBookingQueue().getAppointmentRequestList().add(appointmentRequest);
    }//GEN-LAST:event_BtnReserveActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        ViewReservationJPanel requestViewJPanel = new ViewReservationJPanel(container, account, gymenterprise);
        container.add("requestViewJPanel", requestViewJPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_viewBtnActionPerformed

    private void cbxDateSelectKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxDateSelectKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDateSelectKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnReserve;
    private javax.swing.JButton backjButton;
    private javax.swing.JComboBox cbxDateSelect;
    private javax.swing.JComboBox cbxTimeSlotSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables

    
}
